# Generated by Django 4.2.3 on 2024-12-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Journalist', 'Journalist'), ('Editor', 'Editor'), ('Admin', 'Admin'), ('user', 'User')], max_length=50),
        ),
    ]
