# Generated by Django 4.2.16 on 2024-11-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='article_images/')),
                ('tags', models.CharField(blank=True, choices=[('Politics', 'Politics'), ('Sports', 'Sports'), ('Tech', 'Tech'), ('Health', 'Health')], max_length=100)),
                ('category', models.CharField(choices=[('News', 'News'), ('Opinion', 'Opinion'), ('Feature', 'Feature')], max_length=50)),
                ('publish_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
