# Generated by Django 4.2.16 on 2024-12-03 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('can_submit_article', 'Can submit article'), ('can_review_article', 'Can review article'), ('can_publish_article', 'Can publish article')]},
        ),
    ]
