# Generated by Django 4.2.3 on 2024-12-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to=''),
        ),
    ]
