# Generated by Django 4.2.16 on 2024-12-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_article_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='article_images/'),
        ),
    ]
