# Generated by Django 4.2.16 on 2024-12-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('is_published', 'Is_Published'), ('rejected', 'Rejected')], default='draft', max_length=50),
        ),
    ]
