# Generated by Django 4.2.16 on 2025-01-02 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_article_city_article_latitude_article_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='city',
        ),
        migrations.RemoveField(
            model_name='article',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='article',
            name='longitude',
        ),
    ]
